name: Python Package using Conda on Self-hosted Runner

on: [push]

jobs:
  build:
    runs-on: self-hosted # 更新为使用自托管运行器
    steps:
    - uses: actions/checkout@v3
    - name: Output Python environment
      run: |
        python -m pip list # 输出本地Python环境的已安装包
        python --version   # 输出Python版本
    - name: Save as DOC
      run: |
        python -m pip list > python-packages.doc
        echo "Python Version:" > python-version.doc
        python --version >> python-version.doc
